openapi: '3.0.3'

info:
  title: VIDentigraF
  description: VIDentigraF Private API
  version: 1.0.0
  contact:
    email: support@myrotvorets.center

servers:
  - url: /
    description: Microservice server URL

paths:
  /process:
    post:
      summary: Upload a video.
      description: Upload the video and receive an operation GUID to use with other APIs.
      tags:
        - VIDentigraF API
      requestBody:
        $ref: "videntigraf-common.yaml#/components/requestBodies/upload"
      responses:
        default:
          $ref: "generic-responses.yaml#/components/responses/error_generic"
        "502":
          $ref: "generic-responses.yaml#/components/responses/bad-gateway"
        "200":
          $ref: "videntigraf-common.yaml#/components/responses/successfulUpload"

  /process/{guid}:
    get:
      summary: Retrieve processing status.
      description: |
        To check the status of a video, use the operation GUID to retrieve the processing information. If the video has been successfully processed, you will receive the following information:
        - total number of faces detected;
        - number of faces matched with existing records;
        - total number of archives with detected faces;
        - number of archives with matched faces.
      tags:
        - VIDentigraF API
      operationId: getProcessingStatus
      parameters:
        - $ref: "videntigraf-common.yaml#/components/parameters/guid"
      responses:
        default:
          $ref: "generic-responses.yaml#/components/responses/error_generic"
        "502":
          $ref: "generic-responses.yaml#/components/responses/bad-gateway"
        "200":
          $ref: "videntigraf-common.yaml#/components/responses/processingStatus"

  /process/{guid}/detections/{archive}:
    get:
      summary: Retrieve an archive with captured faces
      description: |
        This API retrieves the archive containing captured faces specified by the `{archive}` parameter for the video identified by the operation GUID.

        Valid values for `{archive}` range from 1 to `d_archives`, which is returned by the [`/process/{guid}`](#/VIDentigraF%20API/getProcessingStatus) API.

        Archives returned by this API need to be concatenated together.
      tags:
        - VIDentigraF API
      operationId: getDetections
      parameters:
        - $ref: "videntigraf-common.yaml#/components/parameters/guid"
        - $ref: "videntigraf-common.yaml#/components/parameters/archive"
      responses:
        default:
          $ref: "generic-responses.yaml#/components/responses/error_generic"
        "502":
          $ref: "generic-responses.yaml#/components/responses/bad-gateway"
        "200":
          $ref: "videntigraf-common.yaml#/components/responses/zipArchive"

  /process/{guid}/matches/{archive}:
    get:
      summary: Retrieve an archive with matched faces
      description: >
        This API retrieves the archive containing matched faces specified by the `{archive}` parameter for the video identified by the operation GUID.

        Valid values for {archive} range from 1 to `m_archives`, which is returned by the [`/process/{guid}`](#/VIDentigraF%20API/getProcessingStatus) API.

        Archives returned by this API need to be concatenated together.
      tags:
        - VIDentigraF API
      operationId: getMatches
      parameters:
        - $ref: "videntigraf-common.yaml#/components/parameters/guid"
        - $ref: "videntigraf-common.yaml#/components/parameters/archive"
      responses:
        default:
          $ref: "generic-responses.yaml#/components/responses/error_generic"
        "502":
          $ref: "generic-responses.yaml#/components/responses/bad-gateway"
        "200":
          $ref: "videntigraf-common.yaml#/components/responses/zipArchive"
