FROM myrotvorets/node:latest@sha256:9619148ecd2d4046c8310721a0ea345ebb72fef41d9a5a1209a4e12dce9f1e2f
USER root
WORKDIR /srv/service
RUN apk add --no-cache vips-dev
COPY ./package.json ./package-lock.json .npmrc .npmrc* ./
RUN npm ci --userconfig .npmrc.local
COPY . .
ENTRYPOINT ["/usr/bin/npm", "run", "start:dev"]
