FROM myrotvorets/node:latest@sha256:7fc7551bd3e6b24cb297e07d4b15c002c7c44e9712f4b51e7307fd56c8d2c85c
USER root
WORKDIR /srv/service
RUN apk add --no-cache vips-dev
COPY ./package.json ./package-lock.json .npmrc .npmrc* ./
RUN npm ci --userconfig .npmrc.local
COPY . .
ENTRYPOINT ["/usr/bin/npm", "run", "start:dev"]
