FROM myrotvorets/node:latest@sha256:b19d07f2df700241278c75cb3f36115c56f674ab78cd0ddc581c0c2a3aee97e1
USER root
WORKDIR /srv/service
RUN apk add --no-cache vips-dev
COPY ./package.json ./package-lock.json .npmrc .npmrc* ./
RUN npm ci --userconfig .npmrc.local
COPY . .
ENTRYPOINT ["/usr/bin/npm", "run", "start:dev"]
