name: Build and Test

on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build and test (Node ${{ matrix.node.name }})
    permissions:
      contents: read
      packages: read
    strategy:
      fail-fast: false
      matrix:
        node:
          - { name: Current, version: current }
          - { name: LTS,     version: lts/* }
    steps:
      - name: Check out the code
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          submodules: true

      - name: Build and test
        uses: myrotvorets/composite-actions/build-test-nodejs@d48d1c16e5782ea32f56fe24da600ca2028ed8b1 # master
        with:
          node-version: ${{ matrix.node.version }}
          registry-url: https://npm.pkg.github.com
